// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package match

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"fmt"
	"github.com/donaldgifford/tbccgolf/views/layout"
)

func NewMatch(tz string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h1>New Match</h1><section><form method=\"post\" hx-swap=\"transition:true\"><input type=\"text\" name=\"Title\" placeholder=\"My Match\" aria-label=\"Text\" required minlength=\"4\" maxlength=\"64\"><fieldset><legend>Scoring Type:</legend> <input type=\"radio\" id=\"net\" name=\"Scoring\" value=\"Net\" checked> <label htmlFor=\"net\">Net</label> <input type=\"radio\" id=\"gross\" name=\"Scoring\" value=\"Gross\"> <label htmlFor=\"gross\">Gross</label></fieldset><fieldset><legend>Holes:</legend> <input type=\"radio\" id=\"9-holes\" name=\"Holes\" value=\"9\" checked> <label htmlFor=\"9-holes\">9 Holes</label> <input type=\"radio\" id=\"18-holes\" name=\"Holes\" value=\"18\"> <label htmlFor=\"18-holes\">18 Holes</label></fieldset><label htmlFor=\"player1\">Player 1</label> <select id=\"player1\" hx-get=\"/api/html/players\" hx-trigger=\"load\" name=\"Player1\" aria-label=\"Select players\" required><option selected disabled value=\"\">Select player 1</option></select> <label htmlFor=\"player2\">Player 2</label> <select id=\"player2\" hx-get=\"/api/html/players\" hx-trigger=\"load\" name=\"Player2\" aria-label=\"Select players\" required><option selected disabled value=\"\">Select player 2</option></select> <label htmlFor=\"player3\">Player 3</label> <select id=\"player3\" hx-get=\"/api/html/players\" hx-trigger=\"load\" name=\"Player3\" aria-label=\"Select players\"><option selected disabled value=\"\">Select player 3</option></select> <label htmlFor=\"player4\">Player 4</label> <select id=\"player4\" hx-get=\"/api/html/players\" hx-trigger=\"load\" name=\"Player4\" aria-label=\"Select players\"><option selected disabled value=\"\">Select player 4</option></select><footer><button>Save</button> <a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 templ.SafeURL = templ.URL(fmt.Sprintf("/matches"))
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var2)))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\">Cancel</a></footer></form></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func CreateIndex(
	title string,
	cmp templ.Component,
) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var4 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			templ_7745c5c3_Err = cmp.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Base(title).Render(templ.WithChildren(ctx, templ_7745c5c3_Var4), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
